### ISSUE TITLE
Problème de routing : register

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/CulturalStore#19]
Quand on est sur une page autre que la homepage (genre /register ou /product) si on clique sur s'inscrire dans le header on se retrouve sur une url du type : http://localhost/culturalstore/app_dev.php/products/register donc une page d'erreur

Je pense que c'est un problème de routing dans le user bundle

**Comment by gzk** [comment]
je ne sais pas si c'est un problème de routing je pense plutôt que le header devrais appeler http://localhost/culturalstore/app_dev.php/register rt non http://localhost/culturalstore/app_dev.php/products/register
